[package]
name = "deps"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
clap = { version = "3.0.0", optional = true }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
near-sdk = { version = "4.0.0" }
near-contract-standards = "4.0.0"

[features]
#core-wasm = ["wasm"]
#wasm = ["near-sdk", "serde_json/arbitrary_precision"]